export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'
export const FETCH_QUIZE_SUCCESS = 'FETCH_QUIZE_SUCCESS'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'
export const QUIZ_RETRY = 'QUIZ_RETRY'
export const QUIZ_FINISH = 'QUIZ_FINISH'

export const ADD_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION'
export const CREATE_QUIZ = 'CREATE_QUIZ'
export const RESET_CREATE_QUIZ = 'RESET_CREATE_QUIZ'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
